// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZawatSys.MicroService.Communication.Infrastructure.Data;

#nullable disable

namespace ZawatSys.MicroService.Communication.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CommunicationDbContext))]
    [Migration("20260420203408_DB0021_AddExternalIdentityBinding")]
    partial class DB0021_AddExternalIdentityBinding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZawatSys.MicroLib.Communication.Domain.Entities.ConversationChannelEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AccessTokenSecretRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUid")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EndpointKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("InboundEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModifiedByUid")
                        .HasColumnType("uuid");

                    b.Property<bool>("OutboundEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("VerificationSecretRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("WebhookSecretRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("IX_ConversationChannelEndpoints_Tenant_IsDeleted");

                    b.HasIndex("TenantId", "Channel", "EndpointKey")
                        .IsUnique()
                        .HasDatabaseName("UX_ConversationChannelEndpoints_Tenant_Channel_EndpointKey");

                    b.HasIndex("TenantId", "Channel", "InboundEnabled")
                        .HasDatabaseName("IX_ConversationChannelEndpoints_Tenant_Channel_InboundEnabled");

                    b.HasIndex("TenantId", "Channel", "IsDefault")
                        .HasDatabaseName("IX_ConversationChannelEndpoints_Tenant_Channel_IsDefault");

                    b.ToTable("ConversationChannelEndpoints", (string)null);
                });

            modelBuilder.Entity("ZawatSys.MicroLib.Communication.Domain.Entities.ExternalIdentityBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("BindingKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("BlockReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationChannelEndpointId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ExternalDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModifiedByUid")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedExternalUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ConversationChannelEndpointId");

                    b.HasIndex("TenantId", "AccountId")
                        .HasDatabaseName("IX_ExternalIdentityBindings_Tenant_AccountId");

                    b.HasIndex("TenantId", "ContactId")
                        .HasDatabaseName("IX_ExternalIdentityBindings_Tenant_ContactId");

                    b.HasIndex("TenantId", "IsBlocked")
                        .HasDatabaseName("IX_ExternalIdentityBindings_Tenant_IsBlocked");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("IX_ExternalIdentityBindings_Tenant_IsDeleted");

                    b.HasIndex("TenantId", "SubjectId")
                        .HasDatabaseName("IX_ExternalIdentityBindings_Tenant_SubjectId");

                    b.HasIndex("TenantId", "ConversationChannelEndpointId", "NormalizedExternalUserId")
                        .IsUnique()
                        .HasDatabaseName("UX_ExternalIdentityBindings_Tenant_Endpoint_NormalizedExternalUserId");

                    b.HasIndex("TenantId", "EntityType", "EntityId")
                        .HasDatabaseName("IX_ExternalIdentityBindings_Tenant_EntityType_EntityId");

                    b.ToTable("ExternalIdentityBindings", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExternalIdentityBindings_BindingKind", "\"BindingKind\" IN ('Verified', 'Inferred', 'Guest', 'Lead')");

                            t.HasCheckConstraint("CK_ExternalIdentityBindings_BlockReason_When_Blocked", "NOT \"IsBlocked\" OR length(trim(coalesce(\"BlockReason\", ''))) > 0");

                            t.HasCheckConstraint("CK_ExternalIdentityBindings_VerificationStatus", "\"VerificationStatus\" IN ('Unverified', 'Verified', 'Suspended')");
                        });
                });

            modelBuilder.Entity("ZawatSys.MicroLib.Shared.Common.Models.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUid")
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModifiedByUid")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Sent")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("SentOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Sent", "OccurredOn")
                        .HasDatabaseName("IX_OutboxMessages_Sent_OccurredOn");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("ZawatSys.MicroLib.Communication.Domain.Entities.ExternalIdentityBinding", b =>
                {
                    b.HasOne("ZawatSys.MicroLib.Communication.Domain.Entities.ConversationChannelEndpoint", "ConversationChannelEndpoint")
                        .WithMany()
                        .HasForeignKey("ConversationChannelEndpointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExternalIdentityBindings_ConversationChannelEndpoints_ConversationChannelEndpointId");

                    b.Navigation("ConversationChannelEndpoint");
                });
#pragma warning restore 612, 618
        }
    }
}
