// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZawatSys.MicroService.Communication.Infrastructure.Data;

#nullable disable

namespace ZawatSys.MicroService.Communication.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CommunicationDbContext))]
    partial class CommunicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZawatSys.MicroLib.Communication.Domain.Entities.ConversationAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedQueueCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AssignmentRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModifiedByUid")
                        .HasColumnType("uuid");

                    b.Property<string>("ReleaseReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "AssignedAt")
                        .HasDatabaseName("IX_ConversationAssignments_ConversationId_AssignedAt");

                    b.HasIndex("ConversationId", "AssignmentRole")
                        .IsUnique()
                        .HasDatabaseName("UX_ConversationAssignments_ConversationId_AssignmentRole_ActiveOwner")
                        .HasFilter("\"IsActive\" = TRUE AND \"AssignmentRole\" = 'Owner'");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("IX_ConversationAssignments_Tenant_IsDeleted");

                    b.HasIndex("TenantId", "AssignedQueueCode", "IsActive")
                        .HasDatabaseName("IX_ConversationAssignments_Tenant_AssignedQueueCode_IsActive");

                    b.HasIndex("TenantId", "AssignedToUserId", "IsActive")
                        .HasDatabaseName("IX_ConversationAssignments_Tenant_AssignedToUserId_IsActive");

                    b.ToTable("ConversationAssignments", null, t =>
                        {
                            t.HasCheckConstraint("CK_ConversationAssignments_AssignmentRole", "\"AssignmentRole\" IN ('Owner', 'Observer')");

                            t.HasCheckConstraint("CK_ConversationAssignments_IsActive_ReleasedAt_Consistency", "\"ReleasedAt\" IS NULL OR NOT \"IsActive\"");

                            t.HasCheckConstraint("CK_ConversationAssignments_ReleaseReason_When_Released", "\"ReleasedAt\" IS NOT NULL OR length(trim(coalesce(\"ReleaseReason\", ''))) = 0");
                        });
                });

            modelBuilder.Entity("ZawatSys.MicroLib.Communication.Domain.Entities.ConversationChannelEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AccessTokenSecretRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUid")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EndpointKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("InboundEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModifiedByUid")
                        .HasColumnType("uuid");

                    b.Property<bool>("OutboundEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("VerificationSecretRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("WebhookSecretRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("IX_ConversationChannelEndpoints_Tenant_IsDeleted");

                    b.HasIndex("TenantId", "Channel", "EndpointKey")
                        .IsUnique()
                        .HasDatabaseName("UX_ConversationChannelEndpoints_Tenant_Channel_EndpointKey");

                    b.HasIndex("TenantId", "Channel", "InboundEnabled")
                        .HasDatabaseName("IX_ConversationChannelEndpoints_Tenant_Channel_InboundEnabled");

                    b.HasIndex("TenantId", "Channel", "IsDefault")
                        .HasDatabaseName("IX_ConversationChannelEndpoints_Tenant_Channel_IsDefault");

                    b.ToTable("ConversationChannelEndpoints", (string)null);
                });

            modelBuilder.Entity("ZawatSys.MicroLib.Communication.Domain.Entities.ConversationControl", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedQueueCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUid")
                        .HasColumnType("uuid");

                    b.Property<string>("HandoffReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long>("IntegrationVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastAIActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastHumanActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastResumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastTakenOverAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastUserActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModifiedByUid")
                        .HasColumnType("uuid");

                    b.Property<string>("PauseReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId")
                        .IsUnique()
                        .HasDatabaseName("UX_ConversationControls_ConversationId");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("IX_ConversationControls_Tenant_IsDeleted");

                    b.HasIndex("TenantId", "AssignedQueueCode", "Mode")
                        .HasDatabaseName("IX_ConversationControls_Tenant_AssignedQueueCode_Mode");

                    b.HasIndex("TenantId", "AssignedToUserId", "Mode")
                        .HasDatabaseName("IX_ConversationControls_Tenant_AssignedToUserId_Mode");

                    b.HasIndex("TenantId", "Mode", "ModifiedAt")
                        .HasDatabaseName("IX_ConversationControls_Tenant_Mode_ModifiedAt");

                    b.ToTable("ConversationControls", null, t =>
                        {
                            t.HasCheckConstraint("CK_ConversationControls_IntegrationVersion_Positive", "\"IntegrationVersion\" > 0");

                            t.HasCheckConstraint("CK_ConversationControls_Mode", "\"Mode\" IN ('AI_ACTIVE', 'HUMAN_ACTIVE', 'AI_PAUSED')");
                        });
                });

            modelBuilder.Entity("ZawatSys.MicroLib.Communication.Domain.Entities.ConversationControlTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("ControlVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModifiedByUid")
                        .HasColumnType("uuid");

                    b.Property<string>("NewMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("NoteRedacted")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreviousMode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("RelatedAIRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelatedMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransitionReason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TriggeredByType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("TriggeredByUserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "OccurredAt")
                        .HasDatabaseName("IX_ConversationControlTransitions_ConversationId_OccurredAt");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("IX_ConversationControlTransitions_Tenant_IsDeleted");

                    b.HasIndex("TenantId", "NewMode", "OccurredAt")
                        .HasDatabaseName("IX_ConversationControlTransitions_Tenant_NewMode_OccurredAt");

                    b.HasIndex("TenantId", "TriggeredByUserId", "OccurredAt")
                        .HasDatabaseName("IX_ConversationControlTransitions_Tenant_TriggeredByUserId_OccurredAt");

                    b.ToTable("ConversationControlTransitions", null, t =>
                        {
                            t.HasCheckConstraint("CK_ConversationControlTransitions_ControlVersion_Positive", "\"ControlVersion\" > 0");

                            t.HasCheckConstraint("CK_ConversationControlTransitions_NewMode", "\"NewMode\" IN ('AI_ACTIVE', 'HUMAN_ACTIVE', 'AI_PAUSED', 'RESOLVED')");

                            t.HasCheckConstraint("CK_ConversationControlTransitions_PreviousMode", "\"PreviousMode\" IS NULL OR \"PreviousMode\" IN ('AI_ACTIVE', 'HUMAN_ACTIVE', 'AI_PAUSED', 'RESOLVED')");

                            t.HasCheckConstraint("CK_ConversationControlTransitions_TriggeredByType", "\"TriggeredByType\" IN ('USER', 'HUMAN', 'AI', 'SYSTEM', 'POLICY')");
                        });
                });

            modelBuilder.Entity("ZawatSys.MicroLib.Communication.Domain.Entities.ConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ConversationChannelEndpointId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUid")
                        .HasColumnType("uuid");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsInternalOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MessageKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModifiedByUid")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderCorrelationKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("RelatedAIRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelatedPendingActionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReplyToMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("SenderDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("SenderUserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TextNormalized")
                        .HasColumnType("text");

                    b.Property<string>("TextRedacted")
                        .HasColumnType("text");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ConversationChannelEndpointId");

                    b.HasIndex("ConversationId", "OccurredAt")
                        .HasDatabaseName("IX_ConversationMessages_ConversationId_OccurredAt");

                    b.HasIndex("ConversationId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("UX_ConversationMessages_ConversationId_Sequence");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("IX_ConversationMessages_Tenant_IsDeleted");

                    b.HasIndex("TenantId", "RelatedAIRequestId")
                        .HasDatabaseName("IX_ConversationMessages_Tenant_RelatedAIRequestId");

                    b.HasIndex("TenantId", "RelatedPendingActionId")
                        .HasDatabaseName("IX_ConversationMessages_Tenant_RelatedPendingActionId");

                    b.HasIndex("TenantId", "ConversationChannelEndpointId", "ProviderMessageId")
                        .IsUnique()
                        .HasDatabaseName("UX_ConversationMessages_Tenant_Endpoint_ProviderMessageId_NotNull")
                        .HasFilter("\"ProviderMessageId\" IS NOT NULL");

                    b.HasIndex("TenantId", "SenderType", "OccurredAt")
                        .HasDatabaseName("IX_ConversationMessages_Tenant_SenderType_OccurredAt");

                    b.ToTable("ConversationMessages", null, t =>
                        {
                            t.HasCheckConstraint("CK_ConversationMessages_Direction", "\"Direction\" IN ('INBOUND', 'OUTBOUND', 'INTERNAL')");

                            t.HasCheckConstraint("CK_ConversationMessages_MessageKind", "\"MessageKind\" IN ('TEXT', 'MEDIA', 'BUTTON_REPLY', 'COMMAND', 'SYSTEM_NOTICE', 'SUGGESTION')");

                            t.HasCheckConstraint("CK_ConversationMessages_SenderType", "\"SenderType\" IN ('USER', 'AI', 'HUMAN', 'SYSTEM')");

                            t.HasCheckConstraint("CK_ConversationMessages_Sequence_NonNegative", "\"Sequence\" >= 0");
                        });
                });

            modelBuilder.Entity("ZawatSys.MicroLib.Communication.Domain.Entities.ConversationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConversationChannelEndpointId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentPendingActionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentScenarioInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentScenarioKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CurrentScenarioStateCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ExternalIdentityBindingId")
                        .HasColumnType("uuid");

                    b.Property<long>("IntegrationVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastAIMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastHumanMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastInboundMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastMessageSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<DateTimeOffset?>("LastOutboundMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastUserMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModifiedByUid")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolutionCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScenarioSnapshotJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<string>("SessionStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ConversationChannelEndpointId");

                    b.HasIndex("ExternalIdentityBindingId", "OpenedAt")
                        .HasDatabaseName("IX_ConversationSessions_ExternalIdentityBindingId_OpenedAt");

                    b.HasIndex("TenantId", "CurrentPendingActionId")
                        .HasDatabaseName("IX_ConversationSessions_Tenant_CurrentPendingActionId");

                    b.HasIndex("TenantId", "ExternalIdentityBindingId")
                        .IsUnique()
                        .HasDatabaseName("UX_ConversationSessions_Tenant_ExternalIdentityBinding_Active")
                        .HasFilter("\"ClosedAt\" IS NULL");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("IX_ConversationSessions_Tenant_IsDeleted");

                    b.HasIndex("TenantId", "SessionStatus", "LastInboundMessageAt")
                        .HasDatabaseName("IX_ConversationSessions_Tenant_SessionStatus_LastInboundMessageAt");

                    b.ToTable("ConversationSessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_ConversationSessions_IntegrationVersion_Positive", "\"IntegrationVersion\" > 0");

                            t.HasCheckConstraint("CK_ConversationSessions_LastMessageSequence_NonNegative", "\"LastMessageSequence\" >= 0");

                            t.HasCheckConstraint("CK_ConversationSessions_SessionStatus", "\"SessionStatus\" IN ('OPEN', 'RESOLVED', 'CLOSED', 'ARCHIVED')");
                        });
                });

            modelBuilder.Entity("ZawatSys.MicroLib.Communication.Domain.Entities.ExternalIdentityBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("BindingKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("BlockReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationChannelEndpointId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ExternalDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModifiedByUid")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedExternalUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ConversationChannelEndpointId");

                    b.HasIndex("TenantId", "AccountId")
                        .HasDatabaseName("IX_ExternalIdentityBindings_Tenant_AccountId");

                    b.HasIndex("TenantId", "ContactId")
                        .HasDatabaseName("IX_ExternalIdentityBindings_Tenant_ContactId");

                    b.HasIndex("TenantId", "IsBlocked")
                        .HasDatabaseName("IX_ExternalIdentityBindings_Tenant_IsBlocked");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("IX_ExternalIdentityBindings_Tenant_IsDeleted");

                    b.HasIndex("TenantId", "SubjectId")
                        .HasDatabaseName("IX_ExternalIdentityBindings_Tenant_SubjectId");

                    b.HasIndex("TenantId", "ConversationChannelEndpointId", "NormalizedExternalUserId")
                        .IsUnique()
                        .HasDatabaseName("UX_ExternalIdentityBindings_Tenant_Endpoint_NormalizedExternalUserId");

                    b.HasIndex("TenantId", "EntityType", "EntityId")
                        .HasDatabaseName("IX_ExternalIdentityBindings_Tenant_EntityType_EntityId");

                    b.ToTable("ExternalIdentityBindings", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExternalIdentityBindings_BindingKind", "\"BindingKind\" IN ('Verified', 'Inferred', 'Guest', 'Lead')");

                            t.HasCheckConstraint("CK_ExternalIdentityBindings_BlockReason_When_Blocked", "NOT \"IsBlocked\" OR length(trim(coalesce(\"BlockReason\", ''))) > 0");

                            t.HasCheckConstraint("CK_ExternalIdentityBindings_VerificationStatus", "\"VerificationStatus\" IN ('Unverified', 'Verified', 'Suspended')");
                        });
                });

            modelBuilder.Entity("ZawatSys.MicroLib.Communication.Domain.Entities.MessageDeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConversationChannelEndpointId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUid")
                        .HasColumnType("uuid");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ErrorMessageRedacted")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsFinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModifiedByUid")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ConversationChannelEndpointId");

                    b.HasIndex("ConversationMessageId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_MessageDeliveryAttempts_ConversationMessageId_AttemptNumber");

                    b.HasIndex("ConversationMessageId", "AttemptedAt")
                        .HasDatabaseName("IX_MessageDeliveryAttempts_ConversationMessageId_AttemptedAt");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("IX_MessageDeliveryAttempts_Tenant_IsDeleted");

                    b.HasIndex("TenantId", "ConversationChannelEndpointId", "ProviderMessageId")
                        .IsUnique()
                        .HasDatabaseName("UX_MessageDeliveryAttempts_Tenant_Endpoint_ProviderMessageId_NotNull")
                        .HasFilter("\"ProviderMessageId\" IS NOT NULL");

                    b.HasIndex("TenantId", "DeliveryStatus", "NextRetryAt")
                        .HasDatabaseName("IX_MessageDeliveryAttempts_Tenant_DeliveryStatus_NextRetryAt");

                    b.ToTable("MessageDeliveryAttempts", null, t =>
                        {
                            t.HasCheckConstraint("CK_MessageDeliveryAttempts_AttemptNumber_Positive", "\"AttemptNumber\" >= 1");

                            t.HasCheckConstraint("CK_MessageDeliveryAttempts_DeliveryStatus", "\"DeliveryStatus\" IN ('QUEUED', 'ACCEPTED', 'SENT', 'DELIVERED', 'READ', 'FAILED')");

                            t.HasCheckConstraint("CK_MessageDeliveryAttempts_IsFinal_FinalizedAt_Consistency", "(\"IsFinal\" AND \"FinalizedAt\" IS NOT NULL) OR (NOT \"IsFinal\" AND \"FinalizedAt\" IS NULL)");
                        });
                });

            modelBuilder.Entity("ZawatSys.MicroLib.Shared.Common.Models.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUid")
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModifiedByUid")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Sent")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("SentOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Sent", "OccurredOn")
                        .HasDatabaseName("IX_OutboxMessages_Sent_OccurredOn");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("ZawatSys.MicroLib.Communication.Domain.Entities.ConversationAssignment", b =>
                {
                    b.HasOne("ZawatSys.MicroLib.Communication.Domain.Entities.ConversationSession", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ConversationAssignments_ConversationSessions_ConversationId");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("ZawatSys.MicroLib.Communication.Domain.Entities.ConversationControl", b =>
                {
                    b.HasOne("ZawatSys.MicroLib.Communication.Domain.Entities.ConversationSession", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ConversationControls_ConversationSessions_ConversationId");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("ZawatSys.MicroLib.Communication.Domain.Entities.ConversationControlTransition", b =>
                {
                    b.HasOne("ZawatSys.MicroLib.Communication.Domain.Entities.ConversationSession", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ConversationControlTransitions_ConversationSessions_ConversationId");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("ZawatSys.MicroLib.Communication.Domain.Entities.ConversationMessage", b =>
                {
                    b.HasOne("ZawatSys.MicroLib.Communication.Domain.Entities.ConversationChannelEndpoint", "ConversationChannelEndpoint")
                        .WithMany()
                        .HasForeignKey("ConversationChannelEndpointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ConversationMessages_ConversationChannelEndpoints_ConversationChannelEndpointId");

                    b.HasOne("ZawatSys.MicroLib.Communication.Domain.Entities.ConversationSession", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ConversationMessages_ConversationSessions_ConversationId");

                    b.Navigation("Conversation");

                    b.Navigation("ConversationChannelEndpoint");
                });

            modelBuilder.Entity("ZawatSys.MicroLib.Communication.Domain.Entities.ConversationSession", b =>
                {
                    b.HasOne("ZawatSys.MicroLib.Communication.Domain.Entities.ConversationChannelEndpoint", "ConversationChannelEndpoint")
                        .WithMany()
                        .HasForeignKey("ConversationChannelEndpointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ConversationSessions_ConversationChannelEndpoints_ConversationChannelEndpointId");

                    b.HasOne("ZawatSys.MicroLib.Communication.Domain.Entities.ExternalIdentityBinding", "ExternalIdentityBinding")
                        .WithMany()
                        .HasForeignKey("ExternalIdentityBindingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ConversationSessions_ExternalIdentityBindings_ExternalIdentityBindingId");

                    b.Navigation("ConversationChannelEndpoint");

                    b.Navigation("ExternalIdentityBinding");
                });

            modelBuilder.Entity("ZawatSys.MicroLib.Communication.Domain.Entities.ExternalIdentityBinding", b =>
                {
                    b.HasOne("ZawatSys.MicroLib.Communication.Domain.Entities.ConversationChannelEndpoint", "ConversationChannelEndpoint")
                        .WithMany()
                        .HasForeignKey("ConversationChannelEndpointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExternalIdentityBindings_ConversationChannelEndpoints_ConversationChannelEndpointId");

                    b.Navigation("ConversationChannelEndpoint");
                });

            modelBuilder.Entity("ZawatSys.MicroLib.Communication.Domain.Entities.MessageDeliveryAttempt", b =>
                {
                    b.HasOne("ZawatSys.MicroLib.Communication.Domain.Entities.ConversationChannelEndpoint", "ConversationChannelEndpoint")
                        .WithMany()
                        .HasForeignKey("ConversationChannelEndpointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_MessageDeliveryAttempts_ConversationChannelEndpoints_ConversationChannelEndpointId");

                    b.HasOne("ZawatSys.MicroLib.Communication.Domain.Entities.ConversationMessage", "ConversationMessage")
                        .WithMany()
                        .HasForeignKey("ConversationMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_MessageDeliveryAttempts_ConversationMessages_ConversationMessageId");

                    b.Navigation("ConversationChannelEndpoint");

                    b.Navigation("ConversationMessage");
                });
#pragma warning restore 612, 618
        }
    }
}
